export const card: string;
export const bg: string;
export const date: string;
export const dark: string;
export const full: string;
export const title: string;
export const expand: string;
export const section: string;
export const fuzzy: string;
